- name: Deploy app to Kubernetes
  hosts: localhost
  vars:
    kubeconfig_path: "/home/jenkins/.kube/config"
    docker_image: "your-dockerhub-username/your-app:{{ lookup('env','BUILD_NUMBER') }}"
  tasks:
    - name: Deploy/update k8s deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
            labels:
              app: my-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                containers:
                - name: my-app
                  image: "{{ docker_image }}"
                  ports:
                  - containerPort: 3000
